# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Subcribe devices on provision profile"
  lane :register_project_devices do
    register_devices(devices_file: "./fastlane//Devices.txt")
    match(type: "development", force_for_new_devices: true)
    match(type: "appstore", force_for_new_devices: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number({
      build_number: latest_testflight_build_number() + 1
    })

    build_app(scheme: "Chargeback", configuration: "Release")
    upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
  end

  desc "Testing Chargeback App"
  lane :tests do
      run_tests(scheme: "Chargeback")
  end
end
